spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    password: 070704
    username: rm550893
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false