spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    password: 070704
    username: rm550893
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    generate-ddl: true
